### ISSUE TITLE
Two Foreign Keys of Users table in Cars table

### ISSUE THREAD

**Issue by abdullahtahir-cs** [Muhammad-Anfaal/smart-parking-system#10]
I have observed that, two userID's as a Foreign Key are forming in database table: **Cars**. one is name: ```userId```, and other is name ```UserUserId```. There should be only one Foreign Key of table: **Users**, name: ```userId```.

**Comment by abdullahtahir-cs** [comment]
I have made a new branch ```two-foreign-keys-of-users```. Do changes on this branch and then create pull request to merge this branch. Update me time by time.
@Muhammad-Anfaal

**Comment by abdullahtahir-cs** [comment]
Keep updating the **back_log** also. 
@Muhammad-Anfaal

**Comment by Muhammad-Anfaal** [comment]
Ok I am working on it
@abdullahtahir-cs

**Comment by Muhammad-Anfaal** [comment]
I have resolved the issue and created a pull request please look in to this.
@abdullahtahir-cs

**Comment by abdullahtahir-cs** [comment]
Yes, it is okay. I am closing the issue now.
