### ISSUE TITLE
Car's number is only getting three alphabetsand three number

### ISSUE THREAD

**Issue by Muhammad-Anfaal** [Muhammad-Anfaal/smart-parking-system#14]
Car's number sould contain three alphabet and upto four digits

**Comment by abdullahtahir-cs** [comment]
If you issue is resolved, then close it also. You can close it from below.
@Muhammad-Anfaal

**Comment by abdullahtahir-cs** [comment]
I am closing this issue as it has been done.
@Muhammad-Anfaal
